[theme]
primaryColor = "#228B22"
backgroundColor = "#000000"
secondaryBackgroundColor = "#111111"
textColor = "#E8E8E8"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"

[server]
port = 8501
headless = true
runOnSave = true
maxUploadSize = 200
